### ISSUE TITLE
有木有可能将智能开关的实时功率显示实现

### ISSUE THREAD

**Issue by Yul-Lee** [sky130/MiWu#12]
目前版本下空调伴侣和智能开关都没办法做到功率的显示
![Screenshot_2024-04-14-11-05-18-180_com xiaomi smarthome](https://github.com/sky130/MiWu/assets/156484695/8b40b40b-796f-4462-bf3e-d6e36d930501)
有时候有查看设备功率的需要（）

**Comment by sky130** [comment]
理论上可行，但是界面太臃肿了，米屋的定位是辅助米家app而不是替代米家app，我考虑考虑
