### ISSUE TITLE
求适配杜亚窗帘

### ISSUE THREAD

**Issue by xudong0612** [sky130/MiWu#14]
求大佬适配智能窗帘
设备名：杜亚智能窗帘m1
控制截图：
![WechatIMG91](https://github.com/sky130/MiWu/assets/619108/d278122e-19d8-4b23-b84b-6e20ed4ce9ba)

**Comment by sky130** [comment]
五一期间会尝试适配

**Comment by sky130** [comment]
已尝试适配

fbef022
