### ISSUE TITLE
设备适配-米家智能除菌加湿器2

### ISSUE THREAD

**Issue by Oldcucumber** [sky130/MiWu#18]
加湿器好像都是一套方法，希望可以适配一下加湿器

**Comment by sky130** [comment]
我记得我适配加湿器了，我回头五一期间看看

**Comment by sky130** [comment]
额，原来我之前适配的是除湿器，你这边有加湿器的界面截图吗？
不然不方便操作

**Comment by Oldcucumber** [comment]
![Screenshot_2024-05-04-22-45-41-77](https://github.com/sky130/MiWu/assets/65931553/23a8e722-d7a7-437e-bab5-a787097e5745)
这样的，可以不管下面那个过湿保护，这个功能不是所有加湿器都有的

**Comment by sky130** [comment]
不用担心，米屋采用的是自适应模式
如果你的设备有这个功能才会提供相应的开关

**Comment by Oldcucumber** [comment]
在加湿器上的物理按钮就两个，一个是开关，一个是挡位切换，是1，2，3和恒湿轮换的，所以大概在定义上恒湿和3个挡位一样是一个挡位而不是一个模式，具体你可以看看接口文档

**Comment by Oldcucumber** [comment]
我觉得在界面上塞一排按钮大概有点臃肿，不行你也可以参考物理控制按钮放一个开关一个轮换也可以）
Belike：
![181aac21454bb23d02476d6dee7de5c](https://github.com/sky130/MiWu/assets/65931553/8ef577e9-b057-45c0-8787-4be217897b2d)

**Comment by sky130** [comment]
这样看来，适配加湿器是一个比较麻烦的事情了

因为`fan-level`居然提供了4个档位

而且`mode`也是分成`档位`和`恒定`两种，这样处理起来比较棘手了

**Comment by sky130** [comment]
合并自然是很好的，但是要将两个不同的属性合并有点麻烦，但是不确定恒定是不是每个加湿器都有，还需要一个判断

**Comment by Oldcucumber** [comment]
恒定挡位是每一个加湿器都有的，我一直用过来的，小米最原始的版本就有恒定模式了

**Comment by sky130** [comment]
但是[智米除菌加湿器1S](https://home.miot-spec.com/s/zhimi.humidifier.va1)就另外一个很奇葩的例子

它没有恒定模式，所以我得做个判断了

这样的例子不在少数

**Comment by Oldcucumber** [comment]
确实，小米自家的都有，但是其他的不一定）
而且我用过的恒湿还支持设置目标湿度，看起来是有点麻烦）

**Comment by sky130** [comment]
那先以你这个设备为基准来适配吧

**Comment by Oldcucumber** [comment]
> 那先以你这个设备为基准来适配吧

我觉得可以，调节湿度范围的功能其实没必要，一般使用上60-70这个范围体验上没什么区别，加上加湿器本身的湿度传感器准确度非常感人（因为传感器在接近地面的位置），实际上就连恒湿这个挡位都用的很少，其实可以先干脆写个没有恒湿模式的界面，后面再研究方案也是可以的

**Comment by sky130** [comment]
那就先考虑档位吧

恒湿写起来不太对头了，仿佛它不应该存在（

**Comment by Oldcucumber** [comment]
没必要，我室内温湿度传感器显示是50左右的适合它告诉我室内湿度80）
恒湿就是个笑话（至少在这种传感器在底部的低端机型上）

**Comment by Oldcucumber** [comment]
所以说有考虑给代码加点注释吗，我本来准备直接改好交个PR的，结果没注释看的我头皮发麻）

**Comment by sky130** [comment]
哪个部分的注释？

**Comment by sky130** [comment]
不知道能不能用咧（

9bc75e1a6c1094d7cabb329e9a4f4b57dea0f0c3

**Comment by Oldcucumber** [comment]
> 哪个部分的注释？

最好有一个项目树，然后剩下的emmm可以随意
（主要是项目树，剩下的按我自己的习惯是注释函数关键实现部分和函数作用）

**Comment by sky130** [comment]
好的，等我弄完就去写一个（

**Comment by sky130** [comment]
13fa6a4f388565cfee3ae6e770ee8e1246bd10a4

**Comment by Oldcucumber** [comment]
> [13fa6a4](https://github.com/sky130/MiWu/commit/13fa6a4f388565cfee3ae6e770ee8e1246bd10a4)

我在试着编译）
但是别急，我还在找正确的JDK版本）

**Comment by sky130** [comment]
https://github.com/sky130/MiWu/wiki/%E9%A1%B9%E7%9B%AE%E6%A0%91

**Comment by Oldcucumber** [comment]
> https://github.com/sky130/MiWu/wiki/%E9%A1%B9%E7%9B%AE%E6%A0%91
> 
> 项目树

额外的，你可能还需要整个构建环境说明了，至少我这边挣扎了半天还是寄了）
（写后端的真是抱歉了）
