### ISSUE TITLE
无法登录 已经确认过手机号和密码是对的 在米家可以登录

### ISSUE THREAD

**Issue by kzysure** [sky130/MiWu#4]
首先感谢您开源这个项目，非常有意义  ，这是我遇到的问题 万分感谢~~~
问题频率 必现
发生时间 2024 0109
设备型号 虚拟机
设备版本 3.1.0.186
软件版本 1.0.3
遇到的问题 ：密码手机号正确的情况下无法登录

**Comment by kzysure** [comment]
后经打包发布  真机可以正常使用，麻烦咨询一下您  android studio虚拟机如何能正常登录呢  ~~~  万分感谢  （本人主要工作是后端开发，可能问题提的比较蠢  感谢感谢）

**Comment by sky130** [comment]
那确实, 你不懂avd的话确实会踩坑, 我这边也没有比较好的解决方法, ~~我也是稀里糊涂的解决了~~, 你可以看看这个搜索结果
https://cn.bing.com/search?q=android+avd%E4%B8%8D%E8%83%BD%E4%B8%8A%E7%BD%91

**Comment by kzysure** [comment]
问题出在 
com.github.miwu.util.OkHttpUtils#isNetSystemUsable 
在avd环境 受到greatwall的影响，被判定为无网络可用  实际访问国内应用是ok的  建议加个avd环境的判定  或者通过ping api的方式  不要用安卓自带的判定网络环境的方案  
再次感谢您的无私开源  界面小而美 非常喜欢

**Comment by sky130** [comment]
现在整个应用框架我正在重写，这个版本太拉跨了

**Comment by kzysure** [comment]
> 现在整个应用框架我正在重写，这个版本太拉跨了

已订阅  感谢您的分享

**Comment by kzysure** [comment]
其实  米家的设备太多了 个人是很难适配齐全的  我感觉   搞个开源项目组估计能好点  小米不做估计是手表用户太小众了。。。。

**Comment by sky130** [comment]
目前我在做一个优化适配啥的，尽量能匹配上所有的设备的基础功能
