### ISSUE TITLE
新版本下米屋依旧无法支持带屏幕的开关的使用

### ISSUE THREAD

**Issue by Yul-Lee** [sky130/MiWu#5]
![S40206-10435495_com xiaomi smarthome](https://github.com/sky130/MiWu/assets/156484695/a14eadf2-12b5-4d00-a721-22e5b0867498)
该开关和温湿度显示在2.0.1版本的米屋下依旧不可用

> 
![PXL_20240206_024433786](https://github.com/sky130/MiWu/assets/156484695/7c309dfa-6d47-4033-b71f-67b39d9e138d)
希望大佬能够支持一下

**Comment by sky130** [comment]
目前开关功能有问题，准备修复，但是我不知道为什么开关会有温湿度传感器（？

**Comment by sky130** [comment]
已经修复了

**Comment by Yul-Lee** [comment]
> 已经修复了

嗯，已经正常使用了
